param = struct(...
    'timestep', 1e-5, ...
    'Rs', 2.5, ...
    'Ld', 0.018, ...
    'Lq', 0.032, ...
    'Lamda_f', 0.30175, ...
    'pole', 6, ...
    'J', 0.00782, ...
    'B', 0.02277, ...
    'Pb', 1000, ...
    'Ibrms', 4.8, ...
    'wb', (2*pi*2000/60)*6/2, ...
    'Ib', 4.8*sqrt(2), ...
    'Vb', 2*1000/(3*4.8*sqrt(2)), ...
    'Zb', [], ...
    'Tb', [], ...
    'Lamdab', [], ...
    'Rspu', [], ...
    'Xdpu', [], ...
    'Xqpu', [], ...
    'Lamda_fpu', [], ...
    'Jpu', [], ...
    'Bpu', [], ...
    'Polepairs', 3,...
    'eta', 10);

% 進一步計算相依變數
param.Zb = param.Vb / param.Ib;
param.Tb = param.Pb / (param.wb * 2 / param.pole);
param.Lamdab = param.Vb / param.wb;
param.Rspu = param.Rs / param.Zb;
param.Xdpu = param.Ld * param.wb / param.Zb;
param.Xqpu = param.Lq * param.wb / param.Zb;
param.Lamda_fpu = param.Lamda_f / param.Lamdab;
param.Jpu = param.J * param.wb / param.Tb;
param.Bpu = param.B * param.wb / param.Tb;


param.k1 = (3/2) * (param.pole/2)^2 / param.J * param.Lamda_f / param.wb;
param.k2 = param.B / param.J;
param.k3 = (param.pole/2) / param.J / param.wb;
param.k4 = param.Rs / param.Lq;
param.k5 = param.Lamda_f * param.wb / (param.Lq * param.Ib);
param.k6 = 1 / param.Lq * param.Vb / param.Ib;
param.k7 = param.Rs / param.Ld;
param.k8 = 1 / param.Ld * param.Vb / param.Ib;
param.k9 = param.Lq / param.Ld * param.wb;
param.k10 = param.Ld / param.Lq * param.wb;
param.k11 = (3/2) * (param.pole/2)^2 / param.J * (param.Ld - param.Lq) * (param.Ib^2) / param.wb;

param.eta = 10;